### ISSUE TITLE
点击加入游戏 没有反应。

### ISSUE THREAD

**Issue by user1121114685** [Mogara/opensgs-ui#8]
不论是项目网页版本 还是自己编译的版本，已经改了地址[.env.production](https://github.com/Mogara/opensgs-ui/blob/main/.env.production) ping 有回应，但是点击加入游戏没有反应

**Comment by bensenx** [comment]
最后一次更新在去年二月，这个项目停摆了吗？

**Comment by user1121114685** [comment]
我也是一脸懵逼。估计做这个还是太难了

**Comment by sunnyadn** [comment]
带宽有限，后面忙起来就没有再开发 😁
